# Generated by Django 5.2.6 on 2025-10-02 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inmuebles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoInmueble",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=120, unique=True)),
            ],
            options={
                "ordering": ["nombre"],
            },
        ),
        migrations.AlterModelOptions(
            name="inmueble",
            options={
                "ordering": ["comuna__region__nombre", "comuna__nombre", "direccion"]
            },
        ),
        migrations.AddField(
            model_name="inmueble",
            name="descripcion",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="inmueble",
            name="tipo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inmuebles",
                to="inmuebles.tipoinmueble",
            ),
        ),
    ]
